# Notes générale
guillaume.collet@univ-rennes.fr

caractere d'echappement \" ou \n, ça change 

Pour que qlq chose and tous doit etre vrai et ca donne vrai

le or au moins un des truc est vrai

A 	B	A AND B		A OR B
T	T	T		T
T	F	F		T
F	T	F		T
F	F	F		F


Quatre chose:

liste: des [], peu se repeter, n'importe quoi,  ordonnée et ça commence a 0

tuple: des (), n'impote quoi, non modifiable, ça sert a python, travail interne de python

Ensemble =set: pas de repetition des {}, un tas d'élément, non ordonné contrairement aux liste, clé de hash et permet de savoir rapidment si un element appartient à l'ensemble, impossible de mettre une liste dans un set.

dico= des {} des , les clé se comporte comme un ensemble donc en desordre et modifiable: info qualitatif associé a une valeur 



# Installation et importation des library

## Methode 1

In [5]:
import icecream

icecream.ic(3)



ic| 3


3

In [6]:
from icecream import ic
ic(3)

ic| 3


3

# 2 ieme partie

Il faudrait installé Anaconda, savoir utilisé anaconda, jupyter est pas mal aussi pour  faire du notbook python (en gros du markdown).
L'inconveniant est qu'on ne pourrait pas tout convertir en script python après.

Conda sert à installé des logicie: conda install nom_logicie

pip est logicile qui permet d'installé des modules: pip install nom_module

In [1]:
# Define the number of rows and columns
num_rows = 10
num_columns = 10

# Create a matrix with initial values set to 0 using list comprehensions
matrix = [[0] * num_columns for _ in range(num_rows)]

    
# Print the resulting matrix
for row in matrix:
    print(row)


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


# NOTE TP 2: Correction forest_fire

On peut utilisé sys


In [4]:
import sys

print(sys.argv)

WI=sys.argv[0]
HE=sys.argv[1]

['c:\\Users\\diall\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ipykernel_launcher.py', '--f=c:\\Users\\diall\\AppData\\Roaming\\jupyter\\runtime\\kernel-v2-51724IvTAQXUxZ6vn.json']


ou input

In [ ]:
import sys
HE=int(input("largeuer"))
print(HE)

Mais le plut élégant est d'utilisé agreparse

**On peut faire un boucle sur l'interface commande**
**Quand on est bloqué sur l'IC on peut taper ctrl + c pour sortire
ce code : [0 for _ in range(width)] est équivalent [0]*width

range exclu la valeur de fin
randit inclu la valeur de fin

pprint(xxxx)
shuffle(xxxx) permet de melangé une liste (xxxx)
.choisis() peut prendre des doublons alors .sample prend des unique

# Range ()
range(stop)
range(start, stop)
range(start, stop, step)

In [ ]:
print(range(10))

print(range(2,10))

print(range(2,10,2))

In [ ]:
liste= range(5)

for i in liste:
    print(i)
print("******************************")
for i in range(2,5):
    print(i)

In [ ]:
liste = list(range(5))
print(liste)

liste = list(range(2,10,2))
print(liste)

# Matrice

In [45]:
matrice= [  [0 for _ in range(5)]  for _ in range (6)]

for i in matrice:
    print(i)

print(len(matrice))
print(len(matrice[0]))
print("********************")
import numpy as np
np_matrice=np.array(matrice)
print(len(np_matrice))
print(len(np_matrice[0]))
print(np_matrice)

for row in range(len(matrice)):
    #print("la ligne est: ",row)
    for col in range(len(matrice)-1):
        #print("la colonne est: ", col)
        if matrice[row][col]==0:
            matrice[row][col]= 55

    


[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
6
5
********************
6
5
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [6]:
from random import randint
for i in range (randint(0,10)):
    print(i)
    


0
1
2
3
4
5


# Fonction lambda,map, filter, reduce,...


In [24]:
ma_fonction = lambda x,y: x+y
print( ma_fonction(2,5) )

7


In [25]:
ma_liste=list(range(1,5))
print(ma_liste)

res= list(map(lambda x: x+x, ma_liste))
print(res)

[1, 2, 3, 4]
[2, 4, 6, 8]


In [28]:
ma_liste=list(range(1,10))
print(ma_liste)

res= list(filter(lambda x: x==1, ma_liste))
print(res)

res= list(filter(lambda x: x % 2 == 0, ma_liste))
print(res)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1]
[2, 4, 6, 8]


In [36]:
from functools import reduce


ma_liste=list(range(1,5))
print(ma_liste)

res= reduce (lambda x,y: x+y, ma_liste)
print(res)

[1, 2, 3, 4]
10
